# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HP_GO7fJnVcAXyRwzqf2qeEjaeztVpaR

##### Liner Regration #####
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

np.random.seed(42)
X = np.random.rand(50,1) * 100
Y = 3.5 * X + np.random.randn(50,1) * 20

model = np.random.seed(42)

model

X

Y = 3.5 * X + np.random.randn(50,1)

Y

LinearRegression()

model = LinearRegression()
model.fit(X, Y)

np.random.seed(42)
X = np.random.rand(50,1) * 100
Y = 3.5 * X + np.random.randn(50,1) * 20

model = LinearRegression()
model.fit(X, Y)
model.predict(X)

Y_pred = model.predict(X)

Y_pred

plt.figure(figsize=(8,6))
plt.scatter(X,Y, color='blue',label='data Points')
plt.plot(X, Y_pred, color='red', linewidth=2,label='Regression Line')
plt.title('Linear Regression on Random dataset')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend()
plt.grid(True)
plt.show()

"""##### Binomial Logistic regression: #####"""

from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
model = LogisticRegression(solver='liblinear', random_state=42)
model.fit(X_train, y_train)

clf = LogisticRegression(max_iter = 10000, random_state = 0)
clf.fit(X_train, y_train)
acc = accuracy_score(y_test, clf.predict(X_test)) * 100

print(f"Logistic Regression model accuracy: {acc: .2f}%")

"""##### Decision Tree #####"""

from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix,classification_report
from sklearn.model_selection import GridSearchCV

iris = load_iris()
X = iris.data
y = iris.target

y = iris.target

y

iris.feature_names

scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.20, random_state=42)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

print(y_train.shape)

clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

con = confusion_matrix(y_test, y_pred)
print(con)

clas = classification_report(y_test, y_pred)
print(clas)

"""##### SVM #####"""

from sklearn.datasets import load_breast_cancer
import matplotlib.pyplot as plt
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.svm import SVC

cancer = load_breast_cancer()
X = cancer.data[:,:2]
y = cancer.target
svm = SVC(kernel='linear', C=1)
svm.fit(X,y)
DecisionBoundaryDisplay.from_estimator(
    svm,
    X,
    response_method="predict",
    alpha=0.8,
    cmap="Pastel1",
    xlabel=cancer.feature_names[0],
    ylabel=cancer.feature_names[1],
)
plt.scatter(X[:,0], X[:,1],
           c=y,
            s=20,edgecolors="k")
plt.show()

"""##### KNN ######"""

import numpy as np
from collections import Counter

def euclidean_distance(point1, point2):
  return np.sqrt(np.sum((np.array(point1) - np.array(point2))**2))

def knn_predict(training_data, training_labels, test_point, k):
  distances = []
  for i in range(len(training_data)):
    distance = euclidean_distance(training_data[i], test_point)
    distances.append((training_labels[i], distance))
  distances.sort(key=lambda x: x[1]) # Sort by distance, not label
  k_nearest_labels = [label for label, _ in distances[:k]]
  return Counter(k_nearest_labels).most_common(1)[0][0]

training_data = [[1,2], [2,3], [3,4], [6,7], [7,8]]
training_labels = ["A", "A", "A", "B", "B"]
test_point = [4, 5]
k = 3

prediction = knn_predict(training_data, training_labels, test_point, k)
print(prediction)

"""##### Random forest #####"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report
import warnings

titanic_data = pd.read_csv('/content/titanic.csv')

warnings.filterwarnings('ignore')
titanic_data = pd.read_csv('/content/titanic.csv')
titanic_data = titanic_data.dropna(subset=['Survived'])

# Select features and target. Ensure correct column names and handle non-numeric data.
X = titanic_data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]
y = titanic_data['Survived']

# Convert 'Sex' column to numerical representation (e.g., 0 for female, 1 for male)
X['Sex'] = X['Sex'].map({'female': 0, 'male': 1})

# Handle missing 'Age' values (e.g., with the mean)
X['Age'].fillna(X['Age'].mean(), inplace=True)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train a RandomForestClassifier model
model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train, y_train)

# Make a prediction on a sample passenger
sample = X_test.iloc[0]
prediction = model_rf.predict(sample.values.reshape(1, -1))

sample_dict = sample.to_dict()
print(f"\nSample Passenger: {sample_dict}")
print(f"Predicted Survival: {'Survived' if prediction[0] == 1 else 'Did Not Survive'}")